### ISSUE TITLE
Gatsby

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/weboftomorrowpodcast.com#14]
# Gatsby

## Description

What is Gatsby? How is it better than a CMS like WordPress or a static site generator like Jekyll?

## Potential guest(s)

@KyleAMathews

## Info

If you haven't heard of Web of Tomorrow before, it's a podcast all about the web, JavaScript, coding, design, and technology. For more information about being a guest, see [this file](/guests.md). Note: we also have and enforce a Code of Conduct for the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and when would be a good time to schedule to record the episode.

If you're interested, I'll need a little information from you for the website. Episode planning happens on the [GitHub repo issues](/issues). Please comment on this issue with the following information (if you'd prefer, you can DM this info to [@agarrharr](https://twitter.com/agarrharr)):

Your name (as you want it on the site)
An email address to share a Google Doc with you
Your twitter handle

Thanks!

**Comment by KyleAMathews** [comment]
Hey, this sounds really fun! Perhaps we could do this around the same time Gatsby 1.0 comes out? That'll be in another month or so.

**Comment by agarrharr** [comment]
Sounds good. I'll keep an eye on the 1.0 milestone. Ping me when it's getting close and we'll schedule a time. Be sure to let me know what timezone you're in as well.

**Comment by KyleAMathews** [comment]
👍

**Comment by agarrharr** [comment]
@KyleAMathews Congrats on Gatsby 1.0! Let me know if you we can schedule something this weekend or next week to record a podcast episode about Gatsby. You can reach me on here or at twitter.com/agarrharr.

**Comment by KyleAMathews** [comment]
Thanks! It took a little while than planned haha. This weekend is busy but
next week there should be some time.
