### ISSUE TITLE
Anki

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/weboftomorrowpodcast.com#16]
# Anki

## Description

How to use Anki to learn new development skills, or brush up on old skills. What is your routine? What benefits have you seen from using Anki?

## Potential guest(s)

@trevordmiller

## Info

If you haven't heard of Web of Tomorrow before, it's a podcast all about the web, JavaScript, coding, design, and technology. For more information about being a guest, see [this file](/guests.md). Note: we also have and enforce a Code of Conduct for the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and when you are available to record.

If you're interested, I'll need a little information from you for the website. Episode planning happens on the [GitHub repo issues](/issues). Please comment on this issue with the following information (if you'd prefer, you can DM this info to [@agarrharr](https://twitter.com/agarrharr)):

Your name (as you want it on the site)
An email address to share a Google Doc with you
Your twitter handle

Thanks!

**Comment by trevordmiller** [comment]
Hey Adam,

Thanks for thinking of me! I’m pretty busy with other priorities currently so I’ll have to pass :) Hope all is well.

Trevor
www.trevordmiller.com <http://www.trevordmiller.com/>

**Comment by agarrharr** [comment]
No problem. Let me know if you ever have some time and are interested. :)
