### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/weboftomorrowpodcast.com#22]
# Webpack

## Description

Why is webpack awesome? Do you need to learn webpack? What's the best way to learn webpack?

## Potential guest(s)

@TheLarkInn @sokra

## Info

If you haven't heard of Web of Tomorrow before, it's a podcast all about the web, JavaScript, coding, design, and technology. For more information about being a guest, see [this file](/guests.md). Note: we also have and enforce a Code of Conduct for the show.

If you've been listed as a potential guest above, please comment on this issue about whether you're interested in coming on to talk about the subject and when you are available to record (as well as what timezone you're in).

If you're interested, I'll need a little information from you for the website. Episode planning happens on the [GitHub repo issues](/issues). Please comment on this issue with the following information (if you'd prefer, you can DM this info to [@agarrharr](https://twitter.com/agarrharr)):

Your name (as you want it on the site)
An email address to share a Google Doc with you
Your twitter handle

Thanks!

**Comment by TheLarkInn** [comment]
Hi @agarrharr. I've been moving my GitHub emails over to a new email and just found this. If you are wanting to schedule something with myself or @sokra, best to reachout via email (sean[dot]larkin[at]microsoft.com)

**Comment by agarrharr** [comment]
Ok, thanks!
