### ISSUE TITLE
Javascript + hardware (DIY IoT stuff)

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/weboftomorrowpodcast.com#5]
@andrewjensen

Dec 17th, 1pm.

What specifically do you want to talk about related to this topic? Is there a project in particular that you've made?

**Comment by andrewjensen** [comment]
Here are some things we could potentially talk about:

## Projects I've worked on

- [Arcade Commander](https://github.com/andrewjensen/arcade-commander-cli)
  - CLI tool to trigger terminal commands from physical buttons, more functionality in the future
- [MIDI Clock Triggers](https://github.com/andrewjensen/midi-clock-triggers)
  - I threw a dance party at my apartment for precisely 17 minutes. This script automatically pressed play and stop on the party playlist.
- [MIDI Techno Lights](https://github.com/andrewjensen/midi-techno-lights)
  - A collaboration with my dad. A project to control Philips Hue lightbulbs from MIDI messages, to sync with music on stage.

## Concepts

- HTTP (RESTful APIs)
- MQTT
- Serial
- MIDI?

## How to learn

- Adafruit, Sparkfun blogs
- Instructibles
- YouTube channels
  - Notes and Volts
- ???

## Dev Boards

- Famous
  - Arduino
  - Raspberry Pi
- Not as famous
  - Teensy
  - Beaglebone
  - Tessel
  - ESP8266

## Getting Parts

- adafruit
- sparkfun
- digikey
- mouser

## Other potential topics

- Third-party APIs for IoT
  - IFTTT
  - AWS
  - etc.
- IBM's Node-Red project (flow-based programming for IoT)

**Comment by agarrharr** [comment]
Thanks, I think we'll have more than enough to talk about.

Here's what I'm thinking about for a basic outline.

What is your background in working with software + hardware?
What is IoT?
What are some things you've built?
What are some good ways to learn or get started with this stuff?
