### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/weboftomorrowpodcast.com#6]
@weapon009

Dec 4th 5pm

We need to narrow down this topic. Some ideas are:

Switching from Angular 1 to 2
Should I learn Angular 1 or 2
Differences between Angular 1 and 2
Why Angular 2 is great
What you don't like about Angular 2
How to get started learning Angular 2
How is Angular 2 different from React
Testing with Angular 2

**Comment by costleya** [comment]
I can do a "Why angular 2 is great".

Other answers in a nutshell:
Switching from 1 to 2 - start over. They are practically different frameworks.
Should learn? 2. 1 has no future.
Differences? They have completely different architectural philosophies. MVC vs Components.
What I don't like - still really new, doesn't support html preprocessors yet
Get started - There is a tutorial, and I love books
How different - Not obsessed with "Make everything javascript!"
Testing - Mocha and Protractor are good for Unit Testing/End-to-End

**Comment by agarrharr** [comment]
Sounds good. "Why Angular 2 is great" it is.

**Comment by agarrharr** [comment]
@weapon009 I just realized you're in a different timezone. So I assume we're doing 5pm your time.

5pm Pacific
6pm Mountain

**Comment by costleya** [comment]
Yes, that is correct.
